apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-plus
  namespace: plus
spec:
  replicas: 1
  selector:
    matchLabels:
      greymatter.io/cluster: edge-plus
  template:
    metadata:
      labels:
        greymatter.io/cluster: edge-plus
      annotations:
        greymatter.io/inject-sidecar-to: '10809'
    spec:
      containers:
      - env:
        - name: XDS_CLUSTER
          value: edge-plus
        - name: ENVOY_ADMIN_LOG_PATH
          value: /dev/stdout
        - name: PROXY_DYNAMIC
          value: "true"
        - name: XDS_ZONE
          value: default-zone
        - name: XDS_HOST
          value: controlensemble.greymatter.svc.cluster.local
        - name: XDS_PORT
          value: "50000"
        image: quay.io/greymatterio/gm-proxy:1.7.0
        imagePullPolicy: Always
        name: sidecar
        ports:
        - containerPort: 10809
          name: proxy
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/proxy/tls/sidecar
          name: tls-certs
      imagePullSecrets:
      - name: gm-docker-secret
      volumes:
      - name: tls-certs
        secret:
          defaultMode: 420
          secretName: gm-edge-ingress-certs
